/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package eventstream.app

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class MessageUtilsTest {
    @Test
    fun testGetMessage() {
        assertEquals("Hello      World!", "Hello      World!")
    }
}
