/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("eventstream.kotlin-library-conventions")

}

dependencies {
    implementation("org.slf4j:slf4j-simple:2.0.3")
    implementation("io.github.oshai:kotlin-logging-jvm:5.1.0")
    api(project(":list"))
}
