package eventstream.beam.transformations

enum class TRANSFORMATION_ENUMS {
    CAPITALIZE_LINE,
    CSV_SERIALIZE_ROWS,
    CATEGORICAL_ANALYSIS,
    CSV_TO_ENTITY_COUNT_FIELDS,
    CSV_TO_ENTITY_TO_PARQUET,
    CSV_TO_ENTITY,
    PARQUET_TO_ENTITY,
    ENTITY_TO_PARQUET
}