/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package eventstream.beam

class MessageUtilsB {
    companion object {
        fun getMessage(): String = "Hello BEAM     World!"
    }
}
